apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mdwiki-api.fullname" . }}-app
  labels:
    {{- include "mdwiki-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.app.jwtSecret | quote }}
  OPENAI_API_KEY: {{ .Values.app.openaiApiKey | quote }}
  LMSTUDIO_API_KEY: {{ .Values.app.lmstudioApiKey | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mdwiki-api.fullname" . }}-postgres
  labels:
    {{- include "mdwiki-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
